[package]
name = "dlt" # Dimensioned Tensor Library
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Library for Vectors and Matrices with Physical Dimensions. Basically `uom` but in a vector space."

[lib]
name = "dlt"# Dimensioned Tensor Library
path = "src/lib.rs"

[dependencies]
rand = "0.9.0"
